
import Foundation

// Contains all information about all courses offered, seperated by subject
struct CourseDatabase {
    // Math courses
    static let mathCourseDetails: [String: Course] = [
        "Algebra I CP": Course(name: "Algebra I CP", subject: "Math", difficulty: "CP", credits: 5, description: "This course is the first in the sequence of high school math classes. Students are introduced to the symbols, language, and concepts which form the basic foundation for later studies in both math and science. Major topics include: techniques for solving first and second degree equations in a single variable, solving linear equations and inequalities in two variables by graphing, solving systems of linear equations, functions, and operations on polynomials, rational expressions and radical expressions."),
        "Geometry CP": Course(name: "Geometry CP", subject: "Math", difficulty: "CP", credits: 5, description: "This course provides the student with the opportunity to develop the two modes of thought: inductive and deductive reasoning. The student studies the roles of definitions, axioms, and theorems in developing a deductive system often by writing proofs. Topics studied via this approach include: concepts of distance, perpendicularity and parallelism, congruence and similarity, circles, areas and volumes of figures in two and three dimensions. The techniques of algebra are employed throughout the course."),
        "Geometry H": Course(name: "Geometry H", subject: "Math", difficulty: "H", credits: 5, description: "This course provides the student with the opportunity to develop the two modes of thought: inductive and deductive reasoning. The student studies the roles of definitions, axioms, and theorems in developing a deductive system often by writing proofs. Topics studied via this approach include: concepts of distance, perpendicularity and parallelism, congruence and similarity, circles, areas and volumes of figures in two and three dimensions, as well as coordinate methods. The techniques of algebra are employed throughout the course"),
        "Algebra II CP": Course(name: "Algebra II CP", subject: "Math", difficulty: "CP", credits: 5, description: "In this second year of algebra, the student extends the skills and concepts started in Algebra I but at a higher level of difficulty. Major topics included in the course are: the field properties of the real numbers; techniques of solving first and second degree equations and inequalities in one and two variables; techniques of simplifying and operating on polynomial, rational, and irrational expressions; linear and quadratic relations and functions; complex numbers; exponential functions; and logarithms; polynomial and radical equations."),
        "Algebra II/Trigonometry CP": Course(name: "Algebra II/Trigonometry CP", subject: "Math", difficulty: "CP", credits: 5, description: "In this second year of algebra, the student extends the skills and concepts started in Algebra I but at a higher level of difficulty. Major topics included in the course are: the field properties of the real numbers; techniques of solving first and second degree equations and inequalities in one and two variables; techniques of simplifying and operating on polynomial, rational, and irrational expressions; linear and quadratic relations and functions; complex numbers; exponential functions; and logarithms; polynomial and radical equations; and introduction to trigonometry"),
        "Algebra II/Trigonometry H": Course(name: "Algebra II/Trigonometry H", subject: "Math", difficulty: "H", credits: 5, description: "In this second year of Algebra, students extend the skills and concepts started in Algebra I but at a higher level of difficulty and with greater emphasis on derivation and proof. Students will explore linear, quadratic, polynomial, radical, rational, exponential, logarithmic and trigonometric functions, their graphs, properties. Skills include manipulating expressions, seeing structure in expressions and solving equations using these functions. Students will also explore the effects of transformations of these functions. Additional topics include complex numbers, sequences and series and their application to real-world problems and analyzing data and applying statistical methods. This course aims to enhance problem-solving skills, critical thinking, and the ability to apply mathematical concepts to real-world situations. Students will engage in both theoretical and practical aspects of algebra, preparing them for advanced mathematics courses and various academic and career pathways."),
        "Algebra III/Trigonometry CP": Course(name: "Algebra III/Trigonometry CP", subject: "Math", difficulty: "CP", credits: 5, description: "The objective of this course is to strengthen the student’s algebra skills and then give a detailed introduction to trigonometry with the goal of preparation for Pre-Calculus. This course includes a review of fundamental concepts of algebra, including real numbers, exponents and radicals, algebraic expressions, fractional expressions, factoring polynomials, complex numbers, and solving systems of equations and inequalities. Particular attention will be given to the concept of a function, including general properties, notation, graphing, transformation, and inverses. Students will also revisit and expand on their understanding of linear, polynomial, exponential, and logarithmic functions. The course will also include an introduction to trigonometric functions and their inverses. If time permits, students will also learn about sequences and series. This course builds an understanding of “real-world” problems, establishing a firm foundation for future work in mathematics and its applications."),
        "Statistics CP": Course(name: "Statistics CP", subject: "Science", difficulty: "CP", credits: 5, description: "This course is an introductory, non-calculus based study of statistics for seniors only.  Students are introduced to major concepts and tools for collecting, analyzing, and drawing conclusions from data.  Graphing calculators are not required but highly recommended."),
        "Precalculus CP": Course(name: "Precalculus CP", subject: "Math", difficulty: "CP", credits: 5, description: "This challenging course provides a sound transition to college-level mathematics. The major topics studied include the elementary functions, which consist of: polynomial, trigonometric, exponential and logarithmic functions. Students also learn how to transform these functions. Sequences, series, conic sections, limits and an introduction to calculus are also studied."),
        "Calculus CP": Course(name: "Calculus CP", subject: "Math", difficulty: "CP", credits: 5, description: "This course is intended for those students who accelerated their math studies in the previous three years and who are ready to begin the study of calculus. It is especially valuable to students who plan to major in business, engineering, mathematics or in the social and life sciences in college. Major emphasis is given to derivatives; curve sketching, exponential and logarithmic functions, integration, trigonometric functions, and differential equations. Extensive applications to biology, medicine, business economics, ecology, social sciences, and physical sciences occur throughout the course."),
        "Precalculus H": Course(name: "Precalculus H", subject: "Math", difficulty: "H", credits: 5, description: "In this second year of Algebra, students extend the skills and concepts started in Algebra I but at a higher level of difficulty and with greater emphasis on derivation and proof. Students will explore linear, quadratic, polynomial, radical, rational, exponential, logarithmic and trigonometric functions, their graphs, properties. Skills include manipulating expressions, seeing structure in expressions and solving equations using these functions. Students will also explore the effects of transformations of these functions. Additional topics include complex numbers, sequences and series and their application to real-world problems and analyzing data and applying statistical methods. This course aims to enhance problem-solving skills, critical thinking, and the ability to apply mathematical concepts to real-world situations. Students will engage in both theoretical and practical aspects of algebra, preparing them for advanced mathematics courses and various academic and career pathways."),
        "AP Precalculus": Course(name: "AP Precalculus", subject: "Math", difficulty: "AP", credits: 5, description: "This challenging course provides a sound transition to college-level mathematics. The major topics studied include the elementary functions which consist of: polynomial, trigonometric, exponential, logarithmic, and parametric functions. Students also learn how to transform these functions. Sequences, series, conic sections, matrices, limits and an introduction to calculus are also studied."),
        "AP Calculus AB": Course(name: "AP Calculus AB", subject: "Math", difficulty: "AP", credits: 5, description: "This course is offered to the student who has had considerable success with previous studies in mathematics and who plans to pursue more advanced work in mathematics, business, engineering, or the physical sciences. Major emphasis is given to the concept of the derivative, the integral, and their applications. Successful completion of this course prepares the student for the Calculus AB Advanced Placement exam."),
        "AP Calculus BC": Course(name: "AP Calculus BC", subject: "Math", difficulty: "AP", credits: 5, description: "This course is offered to the student who has successfully completed the AP Calculus (AB) course. Such a student plans further study in the areas of mathematical sciences, engineering, or physical sciences. The course quickly reviews derivatives, integrals, and their applications. This course also includes topics such as infinite series and differential equations. This course prepares the student for the Calculus BC Advanced Placement Exam."),
        "AP Statistics": Course(name: "AP Statistics", subject: "Math", difficulty: "AP", credits: 5, description: "The purpose of Advanced Placement Statistics is to introduce students to the major concepts and tools for collecting, analyzing, and drawing conclusions from data. Students will be exposed to four broad conceptual themes: exploratory analysis, planning a study, probability, and statistical inference. The AP Statistics course is an excellent option for any student who has successfully completed Pre-Calculus, regardless of the student’s intended college major. Students who successfully complete the course and AP examination may receive college credit and/or advanced placement for an introductory college statistics course. Depending upon the specific college, this course may not satisfy the college’s math requirement for admission."),
        "Selected Topics CP": Course(name: "Selected Topics CP", subject: "Math", difficulty: "CP", credits: 5, description: "This course is an introductory, non-calculus study of a variety of mathematical topics for seniors only.  Students are introduced to major concepts and tools for collecting, analyzing, and drawing conclusions from data.  Students will also explore topics including set theory, number theory, probability, and graph theory. Students will also study topics in Algebra, Functions, Modeling, and Statistics. This is a college preparatory course designed for seniors intending to major in liberal arts, education, or communications.")
    ]
    
    
    // Science courses
    static let scienceCourseDetails: [String: Course] = [
        "Environmental Science CP": Course(name: "Environmental Science CP", subject: "Science", difficulty: "CP", credits: 5, description: "Environmental science is an interdisciplinary science involving the study of human interactions with the living and nonliving world.  It is a practical application of environmental studies that is an interdisciplinary science, meaning it involves many fields of study. Topics include interrelationships and use of the land, air, and water, spheres of the Earth, ecosystems, climate, biodiversity, populations, energy resources, human impacts on the environment, and climate change. The course is a combination of hands-on activities, field experience, and computer modeling."),
        "Biology CP": Course(name: "Biology CP", subject: "Science", difficulty: "CP", credits: 6, description: "This is the field of science in which the student discovers and describes the basic phenomena associated with living things including structure and function, matter and energy transformations, interdependence, heredity, and variation, as well as evolution and biodiversity. Regularly scheduled labs seek to establish a deeper and more comprehensive understanding of the topic."),
        "Geophysical CP": Course(name: "Geophysical CP", subject: "Science", difficulty: "CP", credits: 5, description: "This course presents students with an opportunity to explore physical science topics through real-world geological phenomena, both on Earth and in space. Topics include plate tectonics, earthquakes, the formation of the Earth,  the Big Bang, and the life cycle of stars. Through guided inquiry and research, students will strengthen their proficiency in the NGSS-aligned crosscutting concepts, and science and engineering practices."),
        "Chemistry CP": Course(name: "Chemistry CP", subject: "Science", difficulty: "CP", credits: 6, description: "This phenomena-based course establishes the basic fundamentals of chemistry through both experimental and theoretical processes. Skills are developed using investigation, calculations involving algebraic manipulation and proportions, and laboratory techniques. These skills are developed along with concepts of modern atomic theory and practical applications. Emphasis is placed on the development of the ability to think logically and to solve problems."),
        "Physics CP": Course(name: "Physics CP", subject: "Science", difficulty: "CP", credits: 6, description: "This course presents students with an introduction to a variety of topics in physics, including forces, energy, momentum, electricity, magnetism, and waves. Students will participate in a variety of different activities, such as projects, inquiry-based labs, mathematical problem solving, and scientific argumentation. Upon mastery of the course (per AP Physics I prerequisites), students will have the background necessary for an introductory level college class or AP Physics I."),
        "Environmental Science H": Course(name: "Environmental Science H", subject: "Science", difficulty: "H", credits: 6, description: "Environmental Science is the interdisciplinary study of human interactions with the living and nonliving world. Topics include the interrelationships and the use of the land, air, and water spheres of the Earth, ecosystems, climate, biodiversity, populations, energy resources, and human impact on the environment. Challenging laboratory work is used to introduce and expand topics and to stress the importance of techniques and accurate measurement in science. An outdoor field experience and independent study project are integral components of this course. Students are expected to synthesize information to be able to explain the how and why of scientific phenomena."),
        "Biology H": Course(name: "Biology H", subject: "Science", difficulty: "H", credits: 6, description: "This rigorous course deals extensively with biochemical, physiological, and evolutionary aspects of the living world. Challenging laboratory work is used to introduce and expand topics and to stress the importance of technique and measurement in science. Students are expected to synthesize information to construct written explanations communicating the how and why of scientific phenomena."),
        "Chemistry H": Course(name: "Chemistry H", subject: "Science", difficulty: "H", credits: 6, description: "This rigorous course uses a conceptual and mathematical approach to the topics and concepts of modern chemistry. The principles of atomic theory, quantum chemistry, kinetic theory, equilibrium, bonding, and stoichiometry will serve as the basic “core” of the course. Students are expected to synthesize information to be able to explain the how and why of scientific phenomena."),
        "Physics H": Course(name: "Physics H", subject: "Science", difficulty: "H", credits: 6, description: "The purpose of this course is to give students a broad and thorough introduction to major areas of physics including mechanics, oscillations/wave motion, electricity and magnetism, optics, and modern physics. Challenging problems are used to develop analytical reasoning and an ability to interpret scientific data. Students are expected to synthesize information to be able to explain the how and why of scientific phenomena. The course will prepare students for future academic work in physics (Advanced Placement Physics 2 or C/or college physics). The emphasis in this course is on the algebra and trigonometric-based approach to the above-mentioned areas of physics."),
        "AP Environmental Science": Course(name: "AP Environmental Science", subject: "Science", difficulty: "AP", credits: 7, description: "The AP Environmental Science course is designed to be the equivalent of a one-semester, introductory college course in environmental science. This course provides instruction in Earth systems and resources, the living world, population, land and water use, energy resources and consumption, pollution, and global change. This course provides students with the scientific principles, concepts, and methodologies required to understand the interrelationships of the natural world while emphasizing methods for analyzing and interpreting information and experimental data, including mathematical calculations. This course teaches students how to identify and analyze environmental problems, to evaluate the ecological and human health risks associated with these problems, and to critically examine various solutions for resolving or preventing them. This course includes a laboratory and/or field investigation component. This course has a summer assignment."),
        "AP Chemistry": Course(name: "AP Chemistry", subject: "Science", difficulty: "AP", credits: 7, description: "The AP Chemistry course is designed to be the equivalent of the general chemistry course usually taken during the first college year and is designed to prepare students for the Advanced Placement Chemistry exam. The course covers such topics as: the structure of matter, kinetic theory of gases, chemical equilibrium, chemical kinetics, and the basic principles of thermodynamics. Laboratory work is an important component of this class. Students can expect 5 hours/week of work outside of class. This course has a summer assignment with a test on the summer material on the second day of class."),
        "AP Biology": Course(name: "AP Biology", subject: "Science", difficulty: "AP", credits: 7, description: "The AP Biology course is designed to be the equivalent of the general biology course usually taken during the first college year and is designed to prepare students for the Advanced Placement Biology exam. It stresses rigorous analysis of several major areas of biology as opposed to superficial coverage of many. These areas will include but are not limited to, physiology, molecular biology, evolution, cytology, and genetics. This course has a summer assignment."),
        "AP Physics I": Course(name: "AP Physics I", subject: "Science", difficulty: "AP", credits: 7, description: "The AP Physics 1 course is equivalent to a first-semester college course in algebra-based physics. Course topics include Newtonian mathematics (including rotational dynamics and angular momentum); work, energy, and power; mechanical waves and sound; and an introduction to electric circuits. This course utilizes an inquiry-based instructional approach to develop a deep understanding of foundational physics principles, experimental investigation, abstract reasoning, and problem-solving as it prepares students for the Advanced Placement Physics 1 exam. This course has a summer assignment."),
        "AP Physics II": Course(name: "AP Physics II", subject: "Science", difficulty: "AP", credits: 7, description: "The AP Physics 2 course is equivalent to a second-semester college course in algebra-based physics. Course topics include fluid mechanics, thermodynamics, electricity and magnetism, optics, and atomic and nuclear physics. This course utilizes an inquiry-based instructional approach to develop a deep understanding of foundational physics principles, experimental investigation, abstract reasoning, and problem-solving as it prepares students for the Advanced Placement Physics 2 Exam. This course has a summer assignment."),
        "AP Physics C": Course(name: "AP Physics C", subject: "Science", difficulty: "AP", credits: 7, description: "The AP Physics C course is a college-level calculus-based physics course designed to further refine the skills of abstract reasoning, creativity, experimental investigation, and problem-solving learned in the first year of physics. This course provides a foundation in topics in physics for students interested in future academic work in science, particularly in the fields of engineering, physics, and applied mathematics. The emphasis in this course is on the calculus-based approach to the areas of mechanics, electricity, and magnetism. This course is designed to prepare students for the Advanced Placement Physics C Exam. This course has a summer assignment."),
        "Anatomy & Physiology CP": Course(name: "Anatomy & Physiology CP", subject: "Science", difficulty: "CP", credits: 6, description: "The major focus of this course is human anatomy and physiology. Labs will include dissections. Video conferences, presentations, and projects are an integral component of this course."),
        "Organic Chemistry CP": Course(name: "Organic Chemistry CP", subject: "Science", difficulty: "CP", credits: 5, description: "The course in Organic Chemistry is designed for students interested in continuing their studies in chemistry. Organic Chemistry is an extensive discipline and as such, this course is intended to provide students with a brief survey of some of the topics associated with the chemistry of carbon compounds.  Potential topics include structure and bonding, stereochemistry, reactions and mechanisms, and the methods utilized to investigate chemical reactions. Throughout the course, emphasis is placed on proper and safe laboratory techniques, utilizing experimental investigations to foster student development of critical thinking, abstract reasoning, and quantitative problem solving skills.")
    ]


    // English courses
    static let englishCourseDetails: [String: Course] = [
        "English I CP": Course(name: "English I CP", subject: "English", difficulty: "CP", credits: 5, description: "English I CP focuses on building students’ language literacy.  The thematic approach of the program incorporates exercises in critical reading, writing, listening and speaking in a variety of contexts.  Study units include analysis of novels and short stories, drama, poetry, non-fiction and mythology.  Basics of the writing process are provided and the argumentative research process is taught.  Assessment strategies are an integral part of the course.  In addition, the course of study includes vocabulary development and grammar/usage instruction."),
        "English I H": Course(name: "English I H", subject: "English", difficulty: "H", credits: 5, description: "English I Honors immerses students in the sophisticated elements of reading and writing and elicits their responses to the voices of model authors. The course also covers a basic chronology of literature, which offers students the opportunity to explore  various stages in the evolution of the English language. Students experiment with personal responses that are expressive, persuasive, creative, and informative. They will work with a variety of themes that provide distinct perspectives toward the process."),
        "English II CP": Course(name: "English II CP", subject: "English", difficulty: "CP", credits: 5, description: "English II CP focuses on the reflection of human nature in literature. The class incorporates level-appropriate exercises in critical reading, writing, speaking, and listening in a variety of contexts. Students will study literary genres including poetry, short fiction, the novel, drama, and informational text. Additionally, students will build knowledge of vocabulary and grammatical structures. Throughout the course, students will explore several writing discourses including argumentation, analysis, research writing, and literary nonfiction."),
        "English II H": Course(name: "English II H", subject: "English", difficulty: "H", credits: 5, description: "This second year Honors English course introduces students to Puritan, Romantic, Transcendental, Realistic, Naturalistic, and Modernist literary schools of thought and seeks to develop in students an appreciation for the American Literary traditions. The reading selections of illustrative novels, short stories, poetry, essays, and drama prompt students to explore the following units: Authority vs. Individualism, Self-Reliance and Achievement, Society in Transition, and twentieth century Issues. This list is not exhaustive.  Students are expected to view the works of these periods as reflective of the social, historical, and literary characteristics of the times. The writing component focuses on discourses of definition,cause/effect, compare/contrast, problem/solution, and persuasion with a disciplined approach to both the writing process and structured writing."),
        "English III CP": Course(name: "English III CP", subject: "English", difficulty: "CP", credits: 5, description: "English III CP focuses on the American tradition in literature from the early 1900s to present time.  In addition to addressing issues of social conscience and personal responsibility, English III CP seeks to present an overview of literary movements.  The writing units prompt students to express themselves narratively, persuasively, and reflectively in both timed and researched writings.  Synthesis writing and theme statement writing are another main focus.  Vocabulary development and grammar study are an integral part of the course, along with an overview of assessment strategies."),
        "English III H": Course(name: "English III H", subject: "English", difficulty: "H", credits: 5, description: "Through an intensive study of social, psychological, and cultural issues, students will deepen their ability to read critically and to refine expository writing skills. Required summer readings set the thematic foundation for the year’s work. Students read works from classic and contemporary American authors as an extension of their work during the sophomore year. Writing experiences range from composing a social research proposal to a reflective essay. Advanced vocabulary study requires students to expand their strategies through context, connotation, and degree of meaning. The English III Honors student is expected to demonstrate autonomy, initiative, and commitment to serious literary study and composition."),
        "AP Language and Composition": Course(name: "AP Language and Composition", subject: "English", difficulty: "AP", credits: 5, description: "Advanced Placement English Language and Composition offers students the opportunity to pursue college-level work in exposition and composition. Including considerable summer work, the course has an interdisciplinary focus, drawing on issues in literature, the arts, science, world cultures, government, and philosophy. Students learn from a variety of sources including novels, essays, stories, poems, magazines, newspapers, television programs, and films. Studying advanced writing skills, students will master writing techniques, develop their own style and voice, and prepare for the Advanced Placement Exam."),
        "AP Literature": Course(name: "AP Literature", subject: "English", difficulty: "AP", credits: 5, description: "Advanced Placement Literature offers students the opportunity to pursue college-level work in literature. Drawing from the curriculum authorized by the College Board, students work in an encompassing program, reading a wide variety of selections and responding in discussion and in written analysis. Students have the opportunity to earn college credit by taking the AP Examination near the conclusion of the course."),
        "English IV CP": Course(name: "English IV CP", subject: "English", difficulty: "CP", credits: 5, description: "This course focuses on continuing to develop and expand students’ language literacy.  Most specifically, it engages seniors to examine the circumstances, questions, problems and dilemmas they encounter in the literary world and face in the real world.  Students will build upon skills and experiences in the literacy classroom to develop a mature system of analysis in both literary and psychological landscapes. Additionally, they will research, propose, and defend solutions to problems in society. Students will explore a variety of communication discourses, such as personal essay, literary analysis, proposal/research writing, and definitional persuasion.  Students will be encouraged to develop personal connections and responses to classical drama, modern fiction, informational texts, poetry, music, and contemporary essays."),
        "English IV H": Course(name: "English IV H", subject: "English", difficulty: "H", credits: 5, description: "This course offers students a challenging literary survey, examining the satirical to the serious from classical to post-modern works. The thematic focus, “Provocative Voices,” encourages students to explore issues confronting mankind through a variety of interesting, thought-provoking literary vehicles, including essays, plays, poems, novels, and criticism. The writing component provides students with a variety of experiences paralleling those they will encounter in college writing courses. Students will be expected to research a topic and write a position paper using research to support a thesis statement. Additionally, students will write shorter papers in various discourses and engage in a debate.")
    ]

    
    // History courses
    static let historyCourseDetails: [String: Course] = [
        "World History/Cultures CP": Course(name: "World History/Cultures CP", subject: "History", difficulty: "CP", credits: 5, description: "Students in this course study the historical, political, geographic, and cultural traditions of the world’s people. This class revolves around the interdependence of all the people of the world. The course covers the last 500 years across planet Earth. A consistent emphasis is placed on the dignity, value, and contributions of different societies.  In addition, students will develop skills to analyze primary and secondary sources to craft written and oral arguments."),
        "World History H": Course(name: "World History H", subject: "History", difficulty: "H", credits: 5, description: "World History Honors is an advanced, freshman-level course designed to provide students with an in-depth narrative of events and movements in World History from the end of the Renaissance to the present. Students will investigate the broad themes of intellectual, cultural, and political history and will appreciate how those ideas are reflected in trends of philosophy, popular literature, and the arts. Because events in history can only be understood in terms of their social context, this course will examine demographics and the influences of social classes and gender roles on history. The course will also focus on economic history and the role of industrialization by reviewing the development of commercial practices and changing economic structures to recognize multicultural influences on the world, particularly through an examination of imperialism and colonialism."),
        "US History I CP": Course(name: "US History I CP", subject: "History", difficulty: "CP", credits: 5, description: "This course is designed as a survey of our nation’s early American history. This course examines a chronological survey of the major turning points, issues, people, and events in American history addressing the Pre-colonial and Colonial period, events leading up to the American Revolution, the origins of our Constitution, Reform Movements, Westward Expansion, the Civil War, and the Reconstruction Period. Students will learn fundamental concepts in Geography, Economics, and Civics to gain a better understanding of American history. Students will examine historical documents and materials, utilize primary sources, complete written assessments, as well as conduct historical research to develop as critical thinkers and become more well-rounded members of the community."),
        "US History I H": Course(name: "US History I H", subject: "History", difficulty: "H", credits: 5, description: "World History Honors is an advanced, freshman-level course designed to provide students with an in-depth narrative of events and movements in World History from the end of the Renaissance to the present. Students will investigate the broad themes of intellectual, cultural, and political history and will appreciate how those ideas are reflected in trends of philosophy, popular literature, and the arts. Because events in history can only be understood in terms of their social context, this course will examine demographics and the influences of social classes and gender roles on history. The course will also focus on economic history and the role of industrialization by reviewing the development of commercial practices and changing economic structures to recognize multicultural influences on the world, particularly through an examination of imperialism and colonialism."),
        "US History II CP": Course(name: "US History II CP", subject: "History", difficulty: "CP", credits: 5, description: "This is a full-year course for juniors and seniors who have completed United States History I. This course offers a survey approach to the study of United States History from the late 19th century through the 21st century as America becomes a world power. Some of the topics studied are foreign policy, war, inflation, cities, capitalism, communism, socialism, ethnic diversity, etc. Emphasis is also placed on improving the reading, writing, and speaking skills of students."),
        "AP US History": Course(name: "AP US History", subject: "History", difficulty: "AP", credits: 5, description: "AP U.S. History is designed to provide students with the analytic skills and factual knowledge necessary to deal critically with the problems and materials in U.S. history. The program prepares students for intermediate and advanced college courses by making demands upon them equivalent to those made by full-year introductory college courses. Students should learn to assess historical materials-their relevance to a given interpretive problem, reliability, and importance-and to weigh the evidence using both primary and secondary sources and interpretations presented in historical scholarship. An AP U.S. History course should thus develop the skills necessary to arrive at conclusions on the basis of an informed judgment and to present reasons and evidence clearly and persuasively in essay format. Content ranges from the Gilded Age through the present.  Students may receive college credit based on their score on the AP US History Exam taken in May. Summer work may be required."),
        "AP European History": Course(name: "AP European History", subject: "History", difficulty: "AP", credits: 5, description: "AP European History focuses on developing students’ abilities to think conceptually about European history from approximately 1450 to the present and apply historical thinking skills as they learn about the past. Seven themes of equal importance — the interaction of Europe and the world, economic and commercial developments, cultural and intellectual developments, states and other institutions of power, social organization and development, national and European identity, and technological and scientific innovation — provide areas of historical inquiry for investigation throughout the course. These require students to reason historically about continuity and change over time and make comparisons among various historical developments in different times and places. AP European History is designed to be the equivalent of a two-semester introductory college or university European history course. Summer work may be required."),
        "AP Human Geography": Course(name: "AP Human Geography", subject: "History", difficulty: "AP", credits: 5, description: "Ever wonder why certain towns have multiples of one store but not another? Curious about how location influences your culture and identity? Intrigued by countries around the world and by what you see on the news? Check out AP Human Geography! This course will take you on a global journey where you will learn about the world and topics that are relevant to today’s society by studying patterns and processes that have shaped human understanding, the Earth and the world that we know today. Topics will cover thinking geographically, population and migration, cultural geography, political geography, agricultural geography, urban geography, industrial geography, and more! Through the studies of these themes, you will better understand the modern world and current events."),
        "AP World History": Course(name: "AP World History", subject: "History", difficulty: "AP", credits: 5, description: "The purpose of AP World History is to develop a greater understanding of the evolution of global processes and contacts in different types of human societies. The course highlights the nature of changes in global frameworks and their causes and consequences, as well as comparisons among major societies. It emphasizes relevant factual knowledge, leading interpretive issues, and skills in analyzing historical evidence. The course offers balanced global coverage, with Africa, the Americas, Asia, Europe, and Oceania all represented. Students are encouraged to take the Advanced Placement examination upon completion of this course. Summer work may be required."),
        "AP U.S. Government and Politics": Course(name: "AP U.S. Government and Politics", subject: "History", difficulty: "AP", credits: 5, description: "AP US Government and Politics will give students an analytical perspective on government and politics in the United States. This course includes both the study of general concepts used to interpret U.S. government and politics and the analysis of specific examples. Students will participate in a variety of activities exercising their civic duty, including but not limited to attending public meetings, working on political campaigns, performing community service, and writing letters to the editor. The course also requires familiarity with the various institutions, groups, beliefs, and ideas that constitute U.S. government and politics. Students will become acquainted with a variety of theoretical perspectives and explanations for various behaviors and outcomes. By completing this course, students will know important facts, concepts, and theories pertaining to U.S. government and politics.  They will understand typical patterns of political processes and behavior as well as their consequences (including the components of political behavior, the principles used to explain or justify various government structures and procedures, and the political effects of these structures and procedures).  Students will develop skills in interpreting basic data relevant to U.S. government and politics.  In addition, students will critically analyze relevant theories and concepts, apply them appropriately, and develop their connections across the curriculum."),
        "AP Psychology": Course(name: "AP Psychology", subject: "History", difficulty: "AP", credits: 5, description: "The design of AP Psychology is to introduce students to the systematic and scientific study of the behavior and mental process of human beings and other animals, the biological bases of human behavior, as well as the statistical methods necessary to analyze psychological research. Students are exposed to the psychological facts, principles, and phenomena associated with each of the major subfields within psychology. Students will learn about some of the explorations and discoveries made by psychologists over the past centuries. Students will assess some of the differing approaches and perspectives adopted by psychologists, i.e. biological, behavioral, cognitive, humanistic, psychodynamic, and socio-cultural. Students will gain an appreciation of how psychologists think and their use of critical thinking and analysis. They also learn about the ethics and methods psychologists use in their science and practice. Students are encouraged to take the Advanced Placement Examination upon completion of this course."),
        "AP Microeconomics/AP Macroeconomics": Course(name: "AP Microeconomics/AP Macroeconomics", subject: "History", difficulty: "AP", credits: 5, description: "AP Microeconomics is an introductory college-level microeconomics course. Students cultivate their understanding of the principles that apply to the functions of individual economic decision-makers by using principles and models to describe economic situations and predict and explain outcomes with graphs, charts, and data as they explore concepts like scarcity and markets; costs, benefits, and marginal analysis; production choices and behavior; and market inefficiency and public policy.AP Macroeconomics is an introductory college-level macroeconomics course. Students cultivate their understanding of the principles that apply to an economic system as a whole by using principles and models to describe economic situations and predict and explain outcomes with graphs, charts, and data as they explore concepts like economic measurements, markets, macroeconomic models, and macroeconomic policies. Students are encouraged to take the Advanced Placement examinations in both areas upon completion of this course. Summer work may be required. Algebra and basic calculus are used throughout the curriculum."),
        "Study Hall": Course(name: "Study Hall", subject: "Study Hall", difficulty: "", credits: 0)
    ]
    
    // Language courses
    static let languageCourseDetails: [String: Course] = [
        "Level I CP - " : Course(name: "Level I CP - ", subject: "Language", difficulty: "CP", credits: 5, description: "The broad objective of all levels of modern language study is the development of the three modes of communication: interpersonal, interpretive, and presentational. The first level places particular importance on the presentational and interpersonal skills. Students are prepared to understand the spoken word before they attempt to explore spelling and writing skills. The communication skills are shaped to develop a “personal” kind of communication, so that at the end of the first level, students are able to function in everyday situations in the target language. Interpretive skills are developed through reading and listening practice. Students learn to read, almost immediately, what they have learned to say. The interpersonal and presentational skill of writing is somewhat limited in Level I. Grammar is reinforced through structured exercises based on practical situations. Since culture, the sum total of the beliefs and behavior of a people is best reflected by language, a major emphasis is placed on the appropriate use of language in culturally authentic situations. The Level I world language course is geared to satisfy the requirements of the New Jersey Core Curriculum Content Standards. Cross Content Workplace Readiness skills are emphasized throughout the course as well as the career awareness component are emphasized throughout the course."),
        "Level II CP - " : Course(name: "Level II CP - ", subject: "Language", difficulty: "CP", credits: 5, description: "Level Two is a continuation of Level One, building on the basics presented in the first year. There is a slight shift of emphasis from the listening-speaking aspect of communication to the reading-writing skills; however, all three communication modes continue to be enhanced. Students become much more aware of idiomatic expression, and grammar is covered in more detail in practical situations. The cultures of the target language studied as well as the language to promote interest in and understanding of its inhabitants and satisfaction of the requirements of the world language state standards. Workplace readiness continues to be emphasized as students deepen their skills in this area. The second year satisfies the entrance requirements of most colleges and universities."),
        "Level III CP - " : Course(name: "Level III CP - ", subject: "Language", difficulty: "CP", credits: 5, description: "Level Three is a continuation of Level Two, completing the study of the finer points of grammar and idiomatic expression. The main objective of the third year courses is to enable students to continue to attain a measurable degree of communicative competency and proficiency in each of the three communication modes: interpersonal, interpretive, and presentational. This is made possible through practical exercises and activities that focus on meaningful, personalized communication. Advanced vocabulary is presented in authentic situational contexts. More advanced grammar concepts are presented to form a coherent, cohesive story. Culturally authentic materials are presented to the students for reinforcement of the communication skills. Short selections in literature are studied to introduce students to literary genres and gems of the past. An emphasis is placed on cultural topics reflecting history, customs, traditions and lifestyles of the people whose language is being studied."),
        "Level IV CP - " : Course(name: "Level IV CP - ", subject: "Language", difficulty: "CP", credits: 5, description: "Level Four is a continuation of the first three levels of study. After a comprehensive review of grammar, the subjunctive mode is introduced in culturally authentic situations. Literature,  is studied and analyzed, with careful attention paid to cultural aspects of the language under study. All three communication skills are enhanced through constant practice and presentation on the part of the learner. Fluency in speaking and writing are major components in the fourth level of language study. Authentic materials are used to further immerse the student in the culture of the target language."),
        "AP " : Course(name: "AP ", subject: "Language", difficulty: "AP", credits: 5, description: "The senior advanced course has two main objectives. This course prepares the student for all of the major areas of the Advanced Placement language test. The main emphasis, however, is on the refinement of the three communication modes: interpersonal, interpretive and presentational, with a heavy importance placed on the presentational abilities of the student. Advanced Placement courses are presented on a college level of instruction. Students who complete this course should be able to take intermediate and advanced world language courses when they enter college. Many colleges and universities grant college credit for students who attain successful scores on the Advanced Placement test administered in the spring."),
        "Latin I CP" : Course(name: "Latin I CP", subject: "Language", difficulty: "CP", credits: 5, description: "Latin I provides the basics of Latin vocabulary, grammar and syntax. There is extensive study of the influence of Latin on the English language, as well as on all of the Romance languages. The exploration of the culture and civilization of Ancient Rome is an integral part of the Latin I course. The study of Latin I is especially beneficial in building students’ English vocabulary skills."),
        "Latin II CP" : Course(name: "Latin II CP", subject: "Language", difficulty: "CP", credits: 5, description: "Latin II CP is a continuation of Latin I. All of the vocabulary, grammar and syntax studied in the first year is reviewed and enhanced in the second year. More advanced forms are presented to the students to prepare them to better meet the requirements of the New Jersey Core Curriculum Content Standards. The three modes of communication continue to be stressed, with increasing importance being placed on the presentational skills. Latin II CP satisfies the requirements of many colleges and universities."),
        "Latin III CP" : Course(name: "Latin III CP", subject: "Language", difficulty: "CP", credits: 5, description: "Latin III CP is a continuation of the first two levels of Latin studies. Advanced vocabulary, grammar and syntax are emphasized. The three communication modes are reinforced with an increased emphasis on the interpretive skills in reading masterpieces of Latin literature. Presentational skills are enhanced by original writings in Latin on the part of the students. Latin III CP satisfies the entrance requirements of more demanding colleges and universities."),
        "Latin IV CP" : Course(name: "Latin IV CP", subject: "Language", difficulty: "CP", credits: 5, description: "Latin IV CP is a continuation of the first three levels of Latin studies. Advanced vocabulary, grammar, and syntax are emphasized. Poetry by Ovid, Horace, and Martial, as well as historical writings by Roman emperors, Roman citizens and observers of Roman life are read, analyzed, and compared to present day politics, daily living, and world events and their impacts."),
        "American Sign Language I CP" : Course(name: "American Sign Language I CP", subject: "Language", difficulty: "CP", credits: 5, description: "ASL I is designed to provide students with an introduction to American Sign Language. In ASL I, students will study basic hand shapes, body movements and facial expressions to convey thoughts to other ASL literate individuals. This course focuses on the development of basic vocabulary, structures, and patterns needed for appropriate concept communication through sign language. Along with the linguistic introduction of American Sign Language, the cultural awareness of the Deaf community will be studied on a daily basis."),
        "American Sign Language II CP" : Course(name: "American Sign Language II CP", subject: "Language", difficulty: "CP", credits: 5, description: "ASL II is designed as a continuation of American Sign Language I.  In ASL II, vocabulary and key concepts from the first year will be enhanced and students will continue to study and develop skills related to sentence structure, grammatical rules, and vocabulary. The areas of focus include vocabulary development, sentence structure, sign choice, numbers, phonology, morphology, the use of space, adjectives, nouns, pronouns, non-manual cues, and storytelling. Students will work within the three modes of the language: interpretive, interpersonal, and presentational. Along with the linguistic features of American Sign Language, this course will provide students with a deeper understanding of the history of the Deaf Community while increasing cultural awareness."),
        "American Sign Language III CP" : Course(name: "American Sign Language III CP", subject: "Language", difficulty: "CP", credits: 5, description: "ASL III is a continuation of Level Two, completing the study of the finer points of grammar and idiomatic expression. The main objective of the third year course is to enable students to continue to attain a measurable degree of communicative competency and proficiency in each of the three communication modes: interpersonal, interpretive, and presentational. This is made possible through practical exercises and activities that focus on meaningful, personalized communication. Advanced vocabulary is presented in authentic situational contexts. More advanced grammar concepts are presented to form a coherent, cohesive story. Culturally authentic materials are presented to the students for reinforcement of the communication skills."),
        "American Sign Language IV CP" : Course(name: "American Sign Language IV CP", subject: "Language", difficulty: "CP", credits: 5, description: "ASL IV is a continuation of Level Three, completing the study of the finer points of grammar and idiomatic expression. The main objective of the fourth year course is to enable students to continue to attain a measurable degree of communicative competency and proficiency in each of the three communication modes: interpersonal, interpretive, and presentational. This is made possible through practical exercises and activities that focus on meaningful, personalized communication. Advanced vocabulary is presented in authentic situational contexts. More advanced grammar concepts are presented to form a coherent, cohesive story. Culturally authentic materials are presented to the students for reinforcement of the communication skills."),
        "Study Hall": Course(name: "Study Hall", subject: "Study Hall", difficulty: "", credits: 0)
    ]
    
    
    static let electives: [Elective] = [
        Elective(electiveName: "select", electiveType: "placeholder", allowedGrades: [9,10,11,12], credits: 0, freshman: true),
        Elective(electiveName: "select", electiveType: "placeholder", allowedGrades: [9,10,11,12], credits: 2.5, freshman: true),
        Elective(electiveName: "Accounting I", electiveType: "Career Education", allowedGrades: [10, 11, 12], credits: 5),
        Elective(electiveName: "Advanced Baking I & II", electiveType: "Career Education", allowedGrades: [10, 11, 12], prerequisites: ["Intro to Culinary Arts & Baking", "Baking"]),
        Elective(electiveName: "Advanced Culinary Arts I & II", electiveType: "Career Education", allowedGrades: [10, 11, 12], prerequisites: ["Intro to Culinary Arts & Baking", "Culinary Arts"]),
        Elective(electiveName: "Advanced Drafting", electiveType: "Career Education", allowedGrades: [10, 11, 12], prerequisites: ["Mechanical Drawing"]),
        Elective(electiveName: "Advanced Fashion Design", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], prerequisites: ["Fashion Design"], freshman: true),
        Elective(electiveName: "Advanced Graphic Arts I & II", electiveType: "Career Education", allowedGrades: [10, 11, 12], credits: 5),
        Elective(electiveName: "Advanced Interior Design", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], prerequisites: ["Interior Design"], freshman: true),
        Elective(electiveName: "Advanced Study in Wood Tech", electiveType: "Career Education", allowedGrades: [12], prerequisites: ["Wood Technology I", "Wood Technology II", "Wood Technology III"]),
        Elective(electiveName: "Baking", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], prerequisites: ["Intro to Culinary Arts & Baking"], freshman: true),
        Elective(electiveName: "Business Presentations", electiveType: "Career Education", allowedGrades: [10, 11, 12], freshman: true),
        Elective(electiveName: "Computer Programming I", electiveType: "Career Education", allowedGrades: [10, 11, 12]),
        Elective(electiveName: "Computer Programming II H", electiveType: "Career Education", allowedGrades: [10, 11, 12], prerequisites: ["Computer Programming I"]),
        Elective(electiveName: "AP Computer Science A", electiveType: "Career Education", allowedGrades: [11, 12], credits: 5, prerequisites: ["Computer Programming II H"]),
        Elective(electiveName: "Culinary Arts", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], prerequisites: ["Intro to Culinary Arts & Baking"], freshman: true),
        Elective(electiveName: "Education & Training I & II", electiveType: "Career Education", allowedGrades: [11, 12], credits: 5),
        Elective(electiveName: "Energy & Power Technology", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Entrepreneurship", electiveType: "Career Education", allowedGrades: [10, 11, 12]),
        Elective(electiveName: "Family Living", electiveType: "Career Education", allowedGrades: [10, 11, 12]),
        Elective(electiveName: "Fashion Design", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Financial Literacy", electiveType: "Financial Literacy", allowedGrades: [10, 11, 12]),
        Elective(electiveName: "Interior Design", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Integrative STEM", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Intro to Business", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Into to Culinary Arts & Baking", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Investing", electiveType: "Career Education", allowedGrades: [11, 12],  prerequisites: ["Financial Literacy"]),
        Elective(electiveName: "Law", electiveType: "Career Education", allowedGrades: [10, 11, 12]),
        Elective(electiveName: "Marketing", electiveType: "Career Education", allowedGrades: [10, 11, 12]),
        Elective(electiveName: "Mechanical Drawing", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Nutrition: Healthy Choices", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Sports & Entertainment Marketing", electiveType: "Career Education", allowedGrades: [10, 11, 12], prerequisites: ["Marketing"]),
        Elective(electiveName: "Web Page Design", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Wood Technology I", electiveType: "Career Education", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Wood Technology II", electiveType: "Career Education", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Wood Technology I"]),
        Elective(electiveName: "Wood Technology III", electiveType: "Career Education", allowedGrades: [11, 12], credits: 5, prerequisites: ["Wood Technology II"]),
        Elective(electiveName: "Advanced Drawing", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Art I"], freshman: true),
        Elective(electiveName: "Advanced Guitar I & II", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Guitar"], freshman: true),
        Elective(electiveName: "Advanced Music Technology & Applications", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Music Technology & Applications"], freshman: true),
        Elective(electiveName: "Advanced Photography I", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Photography"], freshman: true),
        Elective(electiveName: "Advanced Sculpture & Ceramics I & II", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Sculpture & Ceramics"], freshman: true),
        Elective(electiveName: "Video & Film I", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Advanced Video & Film I, II, & III", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Video & Film I"]),
        Elective(electiveName: "AP Art History", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5),
        Elective(electiveName: "AP 2D Art and Design", electiveType: "Visual and Performing Arts", allowedGrades: [11, 12], credits: 5, prerequisites: ["Art II"]),
        Elective(electiveName: "AP 2D Art and Design: Photography", electiveType: "Visual and Performing Arts", allowedGrades: [11, 12], credits: 5, prerequisites: ["Advanced Photography"]),
        Elective(electiveName: "AP Drawing", electiveType: "Visual and Performing Arts", allowedGrades: [12], credits: 5, prerequisites: ["AP 2D Art and Design"]),
        Elective(electiveName: "AP Music Theory", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Music Theory I", "Music Theory II"]),
        Elective(electiveName: "Art I", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], credits: 5, freshman: true),
        Elective(electiveName: "Art II", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Art I"]),
        Elective(electiveName: "Cartooning and Animation", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Concert Band", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], credits: 5),
        Elective(electiveName: "Concert Choir", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], credits: 5, freshman: true),
        Elective(electiveName: "Crafts", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Digital Art Design", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Drawing"], freshman: true),
        Elective(electiveName: "Digital Photography", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Drama I", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
//        Elective(electiveName: "Freshman Band", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], credits: 5, freshman: true),
        Elective(electiveName: "Guitar", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Mixed Chorale CP & H", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5),
        Elective(electiveName: "Music Technology & Applications", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Music Theory I", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Music Theory II", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Music Theory I"], freshman: true),
        Elective(electiveName: "Orchesta", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], credits: 5, freshman: true),
        Elective(electiveName: "Painting", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], prerequisites: ["Art I"], freshman: true),
        Elective(electiveName: "Photography", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Portfolio/Advanced Studio Art", electiveType: "Visual and Performing Arts", allowedGrades: [11, 12], prerequisites: ["Art I", "Art II"]),
        Elective(electiveName: "Public Speaking", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Sculpture & Ceramics", electiveType: "Visual and Performing Arts", allowedGrades: [9, 10, 11, 12], freshman: true),
        Elective(electiveName: "Show Choir", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Concert Choir"]),
        Elective(electiveName: "Treble Chorale CP & H", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Concert Choir"]),
        Elective(electiveName: "Wind Ensemble CP & H", electiveType: "Visual and Performing Arts", allowedGrades: [10, 11, 12], credits: 5, prerequisites: ["Concert Band"])
    ]



}
